# configuracion:
  #   resource: "@ConfiguracionBundle/Controller/"
   #  type:     annotation
    # prefix:   /configuracion/

# These first lines load the all routes defined as @Route() annotations in any
# controller defined inside the src/AppBundle/Controller/ directory. Controllers
# are loaded recursively, so you can separate them into subdirectories.
# If you don't like to add annotations in your applications, you can also define
# the routes in YAML, XML or PHP files.
# See http://symfony.com/doc/current/book/routing.html
app:
    resource: @AppBundle/Controller/
    type:     annotation
    #prefix:   /{_locale}
    #requirements:
    #    _locale: %app_locales%
    #defaults:
    #    _locale: %locale%

# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See http://symfony.com/doc/current/cookbook/templating/render_without_controller.html
#homepage:
#    path: /{_locale}
#    requirements:
#        _locale: %app_locales%
#    defaults:
#        _controller: FrameworkBundle:Template:template
#        template:    'default/homepage.html.twig'
#        _locale:     "%locale%"


# Sonata AdminBundle
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# Sonata UserBundle
sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
#saca el panel de usuario
#sonata_user_impersonating:
#    pattern: /admin/dashboard
#    defaults: { _controller: SonataAdminBundle:Core:dashboard }