# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    sonata.admin.consorcio:
      class: Symfonico\ConsorcioBundle\Admin\ConsorcioAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Configuración, label: Consorcios }
      arguments: [null, Symfonico\ConsorcioBundle\Entity\Consorcio, ~]
      calls:
          - [ addChild, [ @sonata.admin.presupuesto ] ]
          - [ addChild, [ @sonata.admin.propiedad ] ]


    sonata.admin.propiedad:
      class: Symfonico\ConsorcioBundle\Admin\PropiedadAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Configuración, label: Propiedades }
      arguments: [null, Symfonico\ConsorcioBundle\Entity\Propiedad, ~]

    sonata.admin.presupuesto:
      class: Symfonico\ConsorcioBundle\Admin\PresupuestoAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Presupuestos, label: Presupuestos }
      arguments: [null, Symfonico\ConsorcioBundle\Entity\Presupuesto, ~]