<?php

namespace Symfonico\ConsorcioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConsorcioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsorcioRepository extends EntityRepository
{
	public function queryOrderByNombre()
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT c
                FROM Symfonico\ConsorcioBundle\:Consorcio c
                ORDER BY c.nombre
            ')
        ;
    }
}
