<?php

namespace Symfonico\ConsorcioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PropiedadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropiedadRepository extends EntityRepository
{
}
